/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWorkspaceRouteImport } from './routes/api/workspace'
import { Route as ApiLlmModelsRouteImport } from './routes/api/llm-models'
import { Route as ApiLlmChatRouteImport } from './routes/api/llm-chat'
import { Route as ApiCliRouteImport } from './routes/api/cli'
import { Route as ApiWebFetchRouteImport } from './routes/api/web-fetch'
import { Route as ApiWebSearchRouteImport } from './routes/api/web-search'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspaceRoute = ApiWorkspaceRouteImport.update({
  id: '/api/workspace',
  path: '/api/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLlmModelsRoute = ApiLlmModelsRouteImport.update({
  id: '/api/llm-models',
  path: '/api/llm-models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLlmChatRoute = ApiLlmChatRouteImport.update({
  id: '/api/llm-chat',
  path: '/api/llm-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCliRoute = ApiCliRouteImport.update({
  id: '/api/cli',
  path: '/api/cli',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebFetchRoute = ApiWebFetchRouteImport.update({
  id: '/api/web-fetch',
  path: '/api/web-fetch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebSearchRoute = ApiWebSearchRouteImport.update({
  id: '/api/web-search',
  path: '/api/web-search',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/cli': typeof ApiCliRoute
  '/api/llm-chat': typeof ApiLlmChatRoute
  '/api/llm-models': typeof ApiLlmModelsRoute
  '/api/workspace': typeof ApiWorkspaceRoute
  '/api/web-fetch': typeof ApiWebFetchRoute
  '/api/web-search': typeof ApiWebSearchRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/cli': typeof ApiCliRoute
  '/api/llm-chat': typeof ApiLlmChatRoute
  '/api/llm-models': typeof ApiLlmModelsRoute
  '/api/workspace': typeof ApiWorkspaceRoute
  '/api/web-fetch': typeof ApiWebFetchRoute
  '/api/web-search': typeof ApiWebSearchRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/cli': typeof ApiCliRoute
  '/api/llm-chat': typeof ApiLlmChatRoute
  '/api/llm-models': typeof ApiLlmModelsRoute
  '/api/workspace': typeof ApiWorkspaceRoute
  '/api/web-fetch': typeof ApiWebFetchRoute
  '/api/web-search': typeof ApiWebSearchRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/cli'
    | '/api/llm-chat'
    | '/api/llm-models'
    | '/api/workspace'
    | '/api/web-fetch'
    | '/api/web-search'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/cli'
    | '/api/llm-chat'
    | '/api/llm-models'
    | '/api/workspace'
    | '/api/web-fetch'
    | '/api/web-search'
  id:
    | '__root__'
    | '/'
    | '/api/cli'
    | '/api/llm-chat'
    | '/api/llm-models'
    | '/api/workspace'
    | '/api/web-fetch'
    | '/api/web-search'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiCliRoute: typeof ApiCliRoute
  ApiLlmChatRoute: typeof ApiLlmChatRoute
  ApiLlmModelsRoute: typeof ApiLlmModelsRoute
  ApiWorkspaceRoute: typeof ApiWorkspaceRoute
  ApiWebFetchRoute: typeof ApiWebFetchRoute
  ApiWebSearchRoute: typeof ApiWebSearchRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspace': {
      id: '/api/workspace'
      path: '/api/workspace'
      fullPath: '/api/workspace'
      preLoaderRoute: typeof ApiWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/llm-models': {
      id: '/api/llm-models'
      path: '/api/llm-models'
      fullPath: '/api/llm-models'
      preLoaderRoute: typeof ApiLlmModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/llm-chat': {
      id: '/api/llm-chat'
      path: '/api/llm-chat'
      fullPath: '/api/llm-chat'
      preLoaderRoute: typeof ApiLlmChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/cli': {
      id: '/api/cli'
      path: '/api/cli'
      fullPath: '/api/cli'
      preLoaderRoute: typeof ApiCliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/web-fetch': {
      id: '/api/web-fetch'
      path: '/api/web-fetch'
      fullPath: '/api/web-fetch'
      preLoaderRoute: typeof ApiWebFetchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/web-search': {
      id: '/api/web-search'
      path: '/api/web-search'
      fullPath: '/api/web-search'
      preLoaderRoute: typeof ApiWebSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiCliRoute: ApiCliRoute,
  ApiLlmChatRoute: ApiLlmChatRoute,
  ApiLlmModelsRoute: ApiLlmModelsRoute,
  ApiWorkspaceRoute: ApiWorkspaceRoute,
  ApiWebFetchRoute: ApiWebFetchRoute,
  ApiWebSearchRoute: ApiWebSearchRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
