/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiWorkspaceRouteImport } from './routes/api/workspace'
import { Route as ApiLlmModelsRouteImport } from './routes/api/llm-models'
import { Route as ApiLlmChatRouteImport } from './routes/api/llm-chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWorkspaceRoute = ApiWorkspaceRouteImport.update({
  id: '/api/workspace',
  path: '/api/workspace',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLlmModelsRoute = ApiLlmModelsRouteImport.update({
  id: '/api/llm-models',
  path: '/api/llm-models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLlmChatRoute = ApiLlmChatRouteImport.update({
  id: '/api/llm-chat',
  path: '/api/llm-chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/llm-chat': typeof ApiLlmChatRoute
  '/api/llm-models': typeof ApiLlmModelsRoute
  '/api/workspace': typeof ApiWorkspaceRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/llm-chat': typeof ApiLlmChatRoute
  '/api/llm-models': typeof ApiLlmModelsRoute
  '/api/workspace': typeof ApiWorkspaceRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/llm-chat': typeof ApiLlmChatRoute
  '/api/llm-models': typeof ApiLlmModelsRoute
  '/api/workspace': typeof ApiWorkspaceRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/llm-chat' | '/api/llm-models' | '/api/workspace'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/llm-chat' | '/api/llm-models' | '/api/workspace'
  id: '__root__' | '/' | '/api/llm-chat' | '/api/llm-models' | '/api/workspace'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiLlmChatRoute: typeof ApiLlmChatRoute
  ApiLlmModelsRoute: typeof ApiLlmModelsRoute
  ApiWorkspaceRoute: typeof ApiWorkspaceRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/workspace': {
      id: '/api/workspace'
      path: '/api/workspace'
      fullPath: '/api/workspace'
      preLoaderRoute: typeof ApiWorkspaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/llm-models': {
      id: '/api/llm-models'
      path: '/api/llm-models'
      fullPath: '/api/llm-models'
      preLoaderRoute: typeof ApiLlmModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/llm-chat': {
      id: '/api/llm-chat'
      path: '/api/llm-chat'
      fullPath: '/api/llm-chat'
      preLoaderRoute: typeof ApiLlmChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiLlmChatRoute: ApiLlmChatRoute,
  ApiLlmModelsRoute: ApiLlmModelsRoute,
  ApiWorkspaceRoute: ApiWorkspaceRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
