/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiLlmModelsRouteImport } from './routes/api/llm-models'
import { Route as ApiLlmChatRouteImport } from './routes/api/llm-chat'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLlmModelsRoute = ApiLlmModelsRouteImport.update({
  id: '/api/llm-models',
  path: '/api/llm-models',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLlmChatRoute = ApiLlmChatRouteImport.update({
  id: '/api/llm-chat',
  path: '/api/llm-chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/llm-chat': typeof ApiLlmChatRoute
  '/api/llm-models': typeof ApiLlmModelsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/llm-chat': typeof ApiLlmChatRoute
  '/api/llm-models': typeof ApiLlmModelsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/llm-chat': typeof ApiLlmChatRoute
  '/api/llm-models': typeof ApiLlmModelsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/llm-chat' | '/api/llm-models'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/llm-chat' | '/api/llm-models'
  id: '__root__' | '/' | '/api/llm-chat' | '/api/llm-models'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiLlmChatRoute: typeof ApiLlmChatRoute
  ApiLlmModelsRoute: typeof ApiLlmModelsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/llm-models': {
      id: '/api/llm-models'
      path: '/api/llm-models'
      fullPath: '/api/llm-models'
      preLoaderRoute: typeof ApiLlmModelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/llm-chat': {
      id: '/api/llm-chat'
      path: '/api/llm-chat'
      fullPath: '/api/llm-chat'
      preLoaderRoute: typeof ApiLlmChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiLlmChatRoute: ApiLlmChatRoute,
  ApiLlmModelsRoute: ApiLlmModelsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
